name: dat-sci-med-unsupervised
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.8.12
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - pip:
    - numpy==1.22.3
    - pandas==1.5.0