name: dat-sci-med-unsupervised
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=12.2.0
  - libpng=1.6.37
  - libstdcxx-ng=12.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numexpr=2.8.1
  - numpy-base=1.21.2
  - openssl=1.1.1s
  - packaging=21.3
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.4
  - pyqt=5.9.2
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - qt=5.9.7
  - readline=8.1.2
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.0
  - tk=8.6.11
  - tornado=6.1
  - wheel=0.37.1
  - xz=5.2.5
  - zstd=1.4.9
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - cffi==1.15.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==0.8.3
    - importlib-resources==5.4.0
    - ipykernel==6.9.1
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-core==4.9.2
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab-pygments==0.1.2
    - lxml==4.8.0
    - markupsafe==2.1.0
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - numpy==1.22.3
    - pandas==1.5.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.3.0
    - scipy==1.8.0
    - send2trash==1.8.0
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - terminado==0.13.3
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - zipp==3.7.0